declare const styles: {
    numberManager: string;
    teams: string;
    welcome: string;
    welcomeImage: string;
    links: string;
    topNavigation: string;
    selected: string;
    dropdownStyles: string;
    totalCountContainer: string;
    totalCount: string;
    resetButton: string;
    detailsListContainer: string;
    modalContainer: string;
    modalHeader: string;
    viewHeader: string;
    editHeader: string;
    modalCloseButton: string;
    modalBody: string;
    modalRow: string;
    modalLabel: string;
    modalValue: string;
    textField: string;
    dropdownField: string;
    modalFooter: string;
    saveButton: string;
    headerRow: string;
    columnHeader: string;
    dataRow: string;
    cell: string;
    'manual-option': string;
    homePage: string;
    rightAlignedDiv: string;
};
export default styles;
//# sourceMappingURL=NumberManager.module.scss.d.ts.map